[project]
name = 'Supply-Chain-Finance-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.factoring]
path = 'contracts/factoring.clar'
clarity_version = 2
epoch = 2.5

[contracts.invoice]
path = 'contracts/invoice.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
